Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2021-08, with the labels that each got.

#52 Turn off IASI MetOp-C 27-29 July 2021 due to observation problem
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/active_channels.tbl
Labels: Non 0-diff, observation configuration

#53 carry MLS T as passive data for x-like exps
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_convinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/obs.rc.tmpl
Labels: 0 diff, enhancement

#54 Update LICENSE.md
  LICENSE.md
Labels: documentation, 0 diff trivial

#55 Feature/rtodling/revise gpsro for 5 29
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_convinfo.txt
  GEOSaana_GridComp/GSI_GridComp/setupbend.f90
  GEOSaana_GridComp/GSI_GridComp/setupcldtot.F90
  GEOSaana_GridComp/GSI_GridComp/setuplwcp.f90
  GEOSaana_GridComp/GSI_GridComp/setupq.f90
  GEOSaana_GridComp/GSI_GridComp/setupswcp.f90
Labels: enhancement, bugfix, Non 0-diff
