Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2021-06, with the labels that each got.

#30 Feature/msienkie/#20 pc scaling
  GEOSaana_GridComp/GSI_GridComp/analyzer
  GEOSaana_GridComp/GSI_GridComp/mksi/pcscaling.db/pcscaling.nml
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/active_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/available_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/iuseClass-4_channels.tbl
Labels: 0 diff

#28 Feature/wrmccart/commercial ro
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_convinfo.txt
  GEOSaana_GridComp/GSI_GridComp/read_gps.f90
  GEOSaana_GridComp/GSI_GridComp/setupbend.f90
Labels: Non 0-diff, enhancement

#33 merge rt-GEOSadas-5_28_0
  GEOSaana_GridComp/GEOSgsi_Coupler/cplr_ensemble.F90
  GEOSaana_GridComp/GEOSgsi_Coupler/geos_StateIO.F90
  GEOSaana_GridComp/GSI_GridComp/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/abstract_ensmod.f90
  GEOSaana_GridComp/GSI_GridComp/advect_cv.f90
  GEOSaana_GridComp/GSI_GridComp/analyzer
  GEOSaana_GridComp/GSI_GridComp/cplr_gfs_ensmod.f90
  GEOSaana_GridComp/GSI_GridComp/derivsmod.f90
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_anavinfo_rcov.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_ozinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_satinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_scaninfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsidiags.rc
  GEOSaana_GridComp/GSI_GridComp/etc/obs.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/general_commvars_mod.f90
  GEOSaana_GridComp/GSI_GridComp/get_gefs_ensperts_dualres.F90
  GEOSaana_GridComp/GSI_GridComp/getsiga.f90
  GEOSaana_GridComp/GSI_GridComp/glbsoi.f90
  GEOSaana_GridComp/GSI_GridComp/gsi_4dvar.f90
  GEOSaana_GridComp/GSI_GridComp/gsi_enscouplermod.f90
  GEOSaana_GridComp/GSI_GridComp/gsi_obOperTypeManager.F90
  GEOSaana_GridComp/GSI_GridComp/gsimod.F90
  GEOSaana_GridComp/GSI_GridComp/hybrid_ensemble_isotropic.F90
  GEOSaana_GridComp/GSI_GridComp/jgrad.f90
  GEOSaana_GridComp/GSI_GridComp/m_extOzone.F90
  GEOSaana_GridComp/GSI_GridComp/m_revBens.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/available.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/active_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/available_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mp_compact_diffs_mod2.f90
  GEOSaana_GridComp/GSI_GridComp/obs_sensitivity.f90
  GEOSaana_GridComp/GSI_GridComp/read_prepbufr.f90
  GEOSaana_GridComp/GSI_GridComp/satthin.F90
  GEOSaana_GridComp/GSI_GridComp/setupoz.f90
  GEOSaana_GridComp/GSI_GridComp/setuprad.f90
  GEOSaana_GridComp/GSI_GridComp/setupt.f90
  GEOSaana_GridComp/GSI_GridComp/stub_ensmod.f90
Labels: Non 0-diff, enhancement

#35 Feature/rtodling/geo sadas 5 28 0 m2
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_tlapmean.txt
  GEOSaana_GridComp/GSI_GridComp/hybrid_ensemble_isotropic.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/active_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/available_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/iuseClass-4_channels.tbl
Labels: Non 0-diff

#31 Scripts to cycle tar file with radiance diags, to spinup radiance bias correction
  GEOSaana_GridComp/GSI_GridComp/extract_diagtarfile.csh
  GEOSaana_GridComp/GSI_GridComp/make_diagtarfile.csh
Labels: 0 diff trivial, enhancement

#36 Feature/rtodling/geo sadas 5 29 0
  CMakeLists.txt
  GEOSaana_GridComp/CMakeLists.txt
  GEOSaana_GridComp/GEOSaana_GridCompMod.F90
  GEOSaana_GridComp/GEOSgsi_Coupler/CMakeLists.txt
  GEOSaana_GridComp/GEOSgsi_Coupler/geos_StateIO.F90
  GEOSaana_GridComp/GEOSgsi_Coupler/geos_pertStateIO.F90
  GEOSaana_GridComp/GSI_GridComp/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/GSI_GridCompMod.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/CMakeLists.txt
Labels: Non 0-diff

#38 Merge changes from GEOSadas-5_29_0 into develop
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_tlapmean.txt
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/active_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/available_channels.tbl
Labels: 0 diff, Non 0-diff

#40 Feature/rtodling/geo sadas 5 29 0
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/available_channels.tbl
Labels: 0 diff trivial

#41 sat-wind (GOES-R) reconfig; supportf for L181 and L91
  GEOSaana_GridComp/GSI_GridComp/etc/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_anavinfo_l181.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_anavinfo_l91.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_convinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x1152y721l132.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x1152y721l181.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x1152y721l91.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x288y181l132.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x288y181l181.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x288y181l91.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x576y361l132.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x576y361l181.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_hybens_info.x576y361l91.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/obs.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/gsimod.F90
  GEOSaana_GridComp/GSI_GridComp/guess_grids.F90
  GEOSaana_GridComp/GSI_GridComp/qcmod.f90
  GEOSaana_GridComp/GSI_GridComp/read_satwnd.f90
Labels: Non 0-diff, enhancement
