Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2021-10, with the labels that each got.

#57 Update LICENSE to Apache, other license changes
  CONTRIBUTING.md
  COPYRIGHT
  LICENSE
  LICENSE-NOSA
  README.md
Labels: documentation, 0 diff trivial

#58 Feature/rtodling/padvect
  GEOSaana_GridComp/GSI_GridComp/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/advect_cv.f90
  GEOSaana_GridComp/GSI_GridComp/analyzer
  GEOSaana_GridComp/GSI_GridComp/antest_maps0.f90
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/glbsoi.f90
  GEOSaana_GridComp/GSI_GridComp/hybrid_ensemble_isotropic.F90
  GEOSaana_GridComp/GSI_GridComp/m_berror_stats.f90
  GEOSaana_GridComp/GSI_GridComp/m_nc_berror.f90
  GEOSaana_GridComp/GSI_GridComp/mpimod.F90
  GEOSaana_GridComp/GSI_GridComp/obs_sensitivity.f90
  GEOSaana_GridComp/GSI_GridComp/test_advpert.f90
  GEOSaana_GridComp/GSI_GridComp/write_bkgvars_grid.f90
Labels: 0 diff structural

#60 NCDIAG and REVISED RO as of x0046
  CONTRIBUTING.md
  COPYRIGHT
  GEOSaana_GridComp/GSI_GridComp/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/advect_cv.f90
  GEOSaana_GridComp/GSI_GridComp/analyzer
  GEOSaana_GridComp/GSI_GridComp/antest_maps0.f90
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_convinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/glbsoi.f90
  GEOSaana_GridComp/GSI_GridComp/hybrid_ensemble_isotropic.F90
  GEOSaana_GridComp/GSI_GridComp/m_berror_stats.f90
  GEOSaana_GridComp/GSI_GridComp/m_nc_berror.f90
  GEOSaana_GridComp/GSI_GridComp/mpimod.F90
  GEOSaana_GridComp/GSI_GridComp/obs_sensitivity.f90
  GEOSaana_GridComp/GSI_GridComp/setupbend.f90
  GEOSaana_GridComp/GSI_GridComp/test_advpert.f90
  GEOSaana_GridComp/GSI_GridComp/write_bkgvars_grid.f90
  LICENSE
  LICENSE-NOSA
  LICENSE.md
  README.md
Labels: 0 diff structural

#59 Feature/msienkie/kxlist cmdline arg prepbykx
  GEOSaana_GridComp/GSI_GridComp/prepbykx.f
Labels: enhancement, 0 diff structural

#62 permanently turn on nc diags; fix for tgas convinfo
  GEOSaana_GridComp/GSI_GridComp/analyzer
  GEOSaana_GridComp/GSI_GridComp/etc/gsi.rc.tmpl
Labels: 0 diff structural
