Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2022-08, with the labels that each got.

#96 minor fix in dealloc
  GEOSaana_GridComp/GSI_GridComp/gsi_metguess_mod.F90
Labels: bugfix, 0 diff trivial

#97 Bugfix/karpob/ozone diag output
  GEOSaana_GridComp/GSI_GridComp/setupoz.f90
Labels: bugfix, 0 diff

#100 Add fixes to pre-2000 gocart emissions and fvsetup + fix to SBUV n19…
  GEOSaana_GridComp/GSI_GridComp/etc/R21C/gmao_global_satinfo.rc
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/GEOSIT/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/GEOSIT/available.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/R21C/active_channels.tbl
Labels: 0 diff trivial

#101 Feature/rtodling/wrtgeovals
  GEOSaana_GridComp/GSI_GridComp/crtm_interface.f90
  GEOSaana_GridComp/GSI_GridComp/genstats_gps.f90
  GEOSaana_GridComp/GSI_GridComp/gsimod.F90
  GEOSaana_GridComp/GSI_GridComp/obsmod.F90
  GEOSaana_GridComp/GSI_GridComp/read_fl_hdob.f90
  GEOSaana_GridComp/GSI_GridComp/read_gps.f90
  GEOSaana_GridComp/GSI_GridComp/read_prepbufr.f90
  GEOSaana_GridComp/GSI_GridComp/read_satwnd.f90
  GEOSaana_GridComp/GSI_GridComp/setupaod.f90
  GEOSaana_GridComp/GSI_GridComp/setupbend.f90
  GEOSaana_GridComp/GSI_GridComp/setupdw.f90
  GEOSaana_GridComp/GSI_GridComp/setuplwcp.f90
  GEOSaana_GridComp/GSI_GridComp/setupoz.f90
  GEOSaana_GridComp/GSI_GridComp/setupps.f90
  GEOSaana_GridComp/GSI_GridComp/setupq.f90
  GEOSaana_GridComp/GSI_GridComp/setuprad.f90
  GEOSaana_GridComp/GSI_GridComp/setuprw.f90
  GEOSaana_GridComp/GSI_GridComp/setupspd.f90
  GEOSaana_GridComp/GSI_GridComp/setupsst.f90
  GEOSaana_GridComp/GSI_GridComp/setupswcp.f90
  GEOSaana_GridComp/GSI_GridComp/setupt.f90
  GEOSaana_GridComp/GSI_GridComp/setuptcp.f90
  GEOSaana_GridComp/GSI_GridComp/setupw.f90
Labels: 0 diff trivial
