Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2022-02, with the labels that each got.

#78 Update gmao_global_tlapmean.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_tlapmean.txt
Labels: 0 diff

#80 Turn off AQUA AIRS channel 305 after 20220111_12z
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/active_channels.tbl
Labels: Non 0-diff, observation configuration

#83 Feature/jguo/convinfo+pcscaling+icld det
  GEOSaana_GridComp/GSI_GridComp/mksi/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/mksi/convinfo.db/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/convinfo.db/available.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/m_actvotype.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/m_icld.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/m_sirest.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/m_sitmpl.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/main.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/pcscaling.db/pcscaling.nml
  GEOSaana_GridComp/GSI_GridComp/mksi/setup.nml
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/icldtable.nml
Labels: enhancement, 0 diff

#84 revise setting for 305 AIRS set off; and set 305 not to be in icld
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/active_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/icldtable.nml
Labels: 0 diff

#85 increase array max size to handle current FPP case - should not need …
  GEOSaana_GridComp/GSI_GridComp/aircraftinfo.f90
Labels: 0 diff trivial

#86 Add EXTENDED_SOURCE flag for prepbykx.f
  GEOSaana_GridComp/GSI_GridComp/CMakeLists.txt
Labels: 0 diff
