Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2022-09, with the labels that each got.

#102 errormod_aircraft small revision
  GEOSaana_GridComp/GSI_GridComp/qcmod.f90
Labels: 0 diff

#103 Feature/karpob/omplp g rename
  GEOSaana_GridComp/GSI_GridComp/etc/GEOSIT/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/GEOSIT/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/R21C/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/R21C/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_ozinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fdda_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_1.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_fgat_2.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsidiags.rc
  GEOSaana_GridComp/GSI_GridComp/etc/obs.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/gsi_obOperTypeManager.F90
  GEOSaana_GridComp/GSI_GridComp/m_extOzone.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/GEOSIT/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/GEOSIT/available.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/R21C/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/R21C/available.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/available.tbl
Labels: 0 diff structural, 0 diff

#104 Bugfix/rtodling/jj says nogood 4ioda
  GEOSaana_GridComp/GSI_GridComp/setupw.f90
Labels: 0 diff trivial

#105 Second round of fixes to GEOSIT resource files
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_convinfo.txt
  GEOSaana_GridComp/GSI_GridComp/mksi/convinfo.db/GEOSIT/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/convinfo.db/R21C/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/convinfo.db/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/convinfo.db/available.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/R21C/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/R21C/available.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/GEOSIT/active_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/GEOSIT/available_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/R21C/active_channels.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/R21C/available_channels.tbl
Labels: 0 diff trivial

#108 Correct sat_altitude value and turn off parallel reading of amsre data.
  GEOSaana_GridComp/GSI_GridComp/read_amsre_gmao.f90
  GEOSaana_GridComp/GSI_GridComp/read_obs.F90
Labels: bugfix, Non 0-diff
