Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2024-09, with the labels that each got.

#155 Incorporate NASA-SPIRE data using SATID
  CHANGELOG.md
  GEOSaana_GridComp/GSI_GridComp/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/prepbysaid.f
Labels: 0 diff

#154 Modify marine PS fix - check PMO quality before substituting for POB
  GEOSaana_GridComp/GSI_GridComp/read_prepbufr.f90
Labels: Non 0-diff

#169 Changes added in GEOS to assimilate CrIS-FSR observations from NOAA-21
  CHANGELOG.md
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_anavinfo_rcov.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_satinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_scaninfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_tlapmean.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
Labels: enhancement, Non 0-diff

#173 Back to errors use in x49 for CrIS npp and n20
  CHANGELOG.md
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_satinfo.txt
Labels: bugfix, Non 0-diff

#127 commit changes for AMSU-A and ATMS switch from Ta to Tb
  CHANGELOG.md
  GEOSaana_GridComp/GSI_GridComp/antcorr_application.f90
  GEOSaana_GridComp/GSI_GridComp/gsimod.F90
  GEOSaana_GridComp/GSI_GridComp/obsmod.F90
  GEOSaana_GridComp/GSI_GridComp/read_atms.f90
  GEOSaana_GridComp/GSI_GridComp/read_bufrtovs.f90
Labels: enhancement, Non 0-diff
