Repository GEOS-ESM/GEOSana_GridComp, pull requests merged in 2024-11, with the labels that each got.

#184 Revise source of OMPS-LP
  CHANGELOG.md
  GEOSaana_GridComp/GSI_GridComp/CMakeLists.txt
  GEOSaana_GridComp/GSI_GridComp/GSI_GridCompMod.F90
  GEOSaana_GridComp/GSI_GridComp/analyzer
  GEOSaana_GridComp/GSI_GridComp/etc/R21C/gmao_global_convinfo.rc
  GEOSaana_GridComp/GSI_GridComp/etc/R21C/gmao_global_satinfo.rc
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_ozinfo.txt
  GEOSaana_GridComp/GSI_GridComp/etc/gsi.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/etc/gsi_sens.rc.tmpl
  GEOSaana_GridComp/GSI_GridComp/m_extOzone.F90
  GEOSaana_GridComp/GSI_GridComp/m_nc_ncepsfc.f90
  GEOSaana_GridComp/GSI_GridComp/write_bkgvars_grid.f90
Labels: enhancement, Non 0-diff

#186 Missed thesechanges from FP patch
  GEOSaana_GridComp/GSI_GridComp/radiance_mod.f90
  GEOSaana_GridComp/GSI_GridComp/setuprad.f90
Labels: enhancement, bugfix, Non 0-diff

#187 Missing in N21 PR
  GEOSaana_GridComp/GSI_GridComp/etc/gsidiags.rc
Labels: enhancement, bugfix, 0 diff

#188 Fix for error associated w/ ch7 GMI
  GEOSaana_GridComp/GSI_GridComp/etc/gmao_global_satinfo.txt
Labels: bugfix, Non 0-diff

#189 M21C DAS update 2
  GEOSaana_GridComp/GSI_GridComp/aircraftinfo.f90
  GEOSaana_GridComp/GSI_GridComp/mksi/convinfo.db/R21C/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/pcscaling.db/pcscaling.nml
  GEOSaana_GridComp/GSI_GridComp/mksi/sidb/R21C/active_channels.tbl
Labels: 0 diff

#183 R21C: Needed to handle OMPS-LP-N21
  GEOSaana_GridComp/GSI_GridComp/etc/R21C/gmao_global_ozinfo.rc
  GEOSaana_GridComp/GSI_GridComp/etc/R21C/prepobs_errtable.global
  GEOSaana_GridComp/GSI_GridComp/m_extOzone.F90
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/R21C/active.tbl
  GEOSaana_GridComp/GSI_GridComp/mksi/ozinfo.db/R21C/available.tbl
Labels: bugfix, Non 0-diff
